# Generated by Django 5.2.1 on 2025-08-27 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_tipo', models.IntegerField(choices=[(1, 'Admin'), (0, 'Usuario')])),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pelicula', models.IntegerField(choices=[(0, 'No Vista'), (1, 'Vista')])),
                ('puntuacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='peliculas_vistas',
            field=models.ManyToManyField(related_name='vista_por', through='core.UsuarioPelicula', to='core.pelicula'),
        ),
    ]
